apiVersion: v1
kind: Pod
metadata:
  name: pts
  labels:
    app: pts
spec:
  containers:
  - image: quay.io/openshift-psap/pts:micro
    command:
      ### Use a wrapper to run the Phoronix Test Suite.
      - /usr/local/bin/pts.sh
      ### Replace by the test you want to run.  If no parameters, sleep.
      #- local/single-threaded-mini
      - local/micro
    name: pts
    imagePullPolicy: IfNotPresent
    #resources:
    #  limits:
    #    cpu: 1
    #    memory: 4Gi
    #securityContext:
    # privileged: true
  ### You may want to run the test suite on a selected (set of) node(s).
  #nodeSelector:
  #  cpu: "1"
  restartPolicy: Never
  ### You may want to use Pod anti-affinity for making sure only one PTS Pod runs on a node at a time.
  #affinity:
  #  podAntiAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #    - labelSelector:
  #        matchExpressions:
  #        - key: app
  #          operator: In
  #          values:
  #          - pts
  #      topologyKey: "kubernetes.io/hostname"
